name: Build and Upload Artifact

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t aurum-image:latest .

    - name: Run Docker container with privileged mode
      run: docker run --privileged --name aurum-container -v ${{ github.workspace }}/output:/output aurum-image:latest

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v2
      with:
        name: iso-artifact
        path: output/
