name: Build and Upload Release

on: 
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t aurum-image:latest .

    - name: Run Docker container with privileged mode
      run: docker run --privileged --name aurum-container -v ${{ github.workspace }}/output:/output aurum-image:latest

    - name: Upload ISO
      uses: actions/upload-artifact@v3
      with:
        name: iso-artifact
        path: output/
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: aurumOS-${{ github.ref }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
